### ISSUE TITLE
Ignoring words is slow

### ISSUE THREAD

**Issue by asfaltboy** [zcold/ignore_words#3]
Seems to take around 3/4 seconds each time I ignore a word, and it freezes the UI. This perhaps can be solved by using an async call?

By the way, I'm on OSX and the plugin works very well for me (besides this issue).

**Comment by zcold** [comment]
thank you for your report.
Currently I am busy with my work things and I will probability fix it in
the next month.

**Comment by asfaltboy** [comment]
Played around with async, but even when split into parts, reloading settings is about the same slow. Unsure how we can further improve this.

**Comment by asfaltboy** [comment]
Oops, I honestly didn't notice but seems that ST3 (Build 3080, Release Date: 24 March 2015) fixed the issue with ignored words not persisting. So if using that build or newer, `ignore_words` is not really required.
